version: '3.4'

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "127.0.0.1:9090:9090"
  pushgateway:
    image: prom/pushgateway
    ports:
      - "0.0.0.0:9091:9091"
  grafana:
    image: grafana/grafana:latest

    ports:
      - "127.0.0.1:3000:3000"