{
 "title": "ttestSuite",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(expected_file_count,job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Basic Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Remaining Files",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ttestsuite_compr_input_file_count{job=\"$job\"}-ttestsuite_compr_processed_files_count{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Input Files",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ttestsuite_compr_input_file_count{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Expected Remaining Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 7, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(ttestsuite_compr_input_file_count{job=\"$job\"}-ttestsuite_compr_processed_files_count{job=\"$job\"})/rate(ttestsuite_compr_processed_files_count{job=\"$job\"}[4m])"
    }
   ]
  },
  { "title": "Ttest Results", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "XCorr Random against Prefix",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ttestsuite_compr_xcorr_against_random_prefix{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "XCorr Fixed against Prefix",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ttestsuite_compr_xcorr_against_fixed_prefix{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Max T Value",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ttestsuite_compr_max_test_value{job=\"$job\"}"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Read Files Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "Files/sec" }
   ],
   "targets": [
    {
     "expr": "rate(ttestsuite_compr_read_files_count{job=\"$job\"}[20s])"
    }
   ]
  },
  {
   "title": "Processed Files Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "Files/sec" }
   ],
   "targets": [
    {
     "expr": "rate(ttestsuite_compr_processed_files_count{job=\"$job\"}[20s])"
    }
   ]
  },
  {
   "title": "Free Slots Input Queue",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ttestsuite_compr_input_queue_free_slots{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Free Slots QualityControl Queue",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ttestsuite_compr_qq_queue_free_slots{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Snapshotter Wait List Entries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ttestsuite_compr_ss_wait_queue_size{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Snapshotter Input Queue Free Slots",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ttestsuite_compr_ss_input_queue_free_slots{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Used memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Go GC ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Go Routines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"$job\"}"
    }
   ]
  }
 ]
}